apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: fib-knative-config
spec:
  template:
    metadata: 
      labels:
        knative.dev/type: container
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: us.icr.io/mofi-cr/fib-knative:v1
          env:
            - name: version
              value: v1