apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: fib-knative
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/IBM/fib-knative.git
              revision: master
          template:
            name: kaniko
            arguments:
            - name: IMAGE
              value: us.icr.io/mofi/fib-knative:v1
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "10"
        spec:
          serviceAccountName: build-bot
          container:
            image: us.icr.io/mofi/fib-knative:v1
            imagePullPolicy: Always