apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: fib-knative
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: moficodes/fib-knative:v0