apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: fib-knative-image-v1
spec:
  type: image
  params:
    - name: url
      value: us.icr.io/mofi-cr/fib-knative:v1
      #image that starts fibonacci number at 0