apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: fib-knative-git-v2
spec:
  type: git
  params:
    - name: revision
      value: vnext
    - name: url
      value: https://github.com/IBM/fib-knative