apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-build-v1
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/IBM/fib-knative.git
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: us.icr.io/mofi/fib-knative:build-1