apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    build.knative.dev/docker-0: us.icr.io
type: kubernetes.io/basic-auth
data:
  # Use 'echo -n "username" | base64' to generate this string
  username: <docker-user-name-base-64>
  # Use 'echo -n "password" | base64' to generate this string
  password: <docker-password-base-64>